import { GoogleGenerativeAI } from "@google/generative-ai"

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || "")

export async function generateSticker(
  imageBase64: string,
  stylePrompt: string
): Promise<string> {
  const model = genAI.getGenerativeModel({
    model: "gemini-2.0-flash-exp",
    generationConfig: {
      responseModalities: ["image", "text"],
    } as any,
  })

  const result = await model.generateContent({
    contents: [
      {
        role: "user",
        parts: [
          {
            inlineData: {
              mimeType: "image/jpeg",
              data: imageBase64,
            },
          },
          {
            text: stylePrompt,
          },
        ],
      },
    ],
  })

  const response = result.response
  const candidates = response.candidates

  if (!candidates || candidates.length === 0) {
    throw new Error("No response from Gemini API")
  }

  const parts = candidates[0].content.parts

  for (const part of parts) {
    if ((part as any).inlineData) {
      return (part as any).inlineData.data
    }
  }

  throw new Error("No image generated by Gemini API")
}
