import { GoogleGenerativeAI } from "@google/generative-ai"

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || "")

// Gemini 2.5 Flash Image (aka "Nano Banana") — the actual image generation model.
// This is NOT the same as gemini-2.0-flash-exp which is a text/multimodal model.
const IMAGE_MODEL = "gemini-2.5-flash-image-preview"

const TRANSPARENT_PNG_INSTRUCTION = `
CRITICAL OUTPUT REQUIREMENTS:
- Output format: transparent PNG
- Background: fully transparent (alpha channel = 0 outside the subject)
- NO solid background, NO gradient, NO scene
- Just the subject with clean edges, floating on transparency
- This image will be kiss-cut into a sticker — the cutter traces the alpha channel
- If there is any background, the sticker will be printed as a rectangle (wrong)
`.trim()

export async function generateSticker(
  imageBase64: string,
  stylePrompt: string
): Promise<string> {
  const model = genAI.getGenerativeModel({
    model: IMAGE_MODEL,
    generationConfig: {
      responseModalities: ["image", "text"],
    } as any,
  })

  const fullPrompt = `${stylePrompt}\n\n${TRANSPARENT_PNG_INSTRUCTION}`

  const result = await model.generateContent({
    contents: [
      {
        role: "user",
        parts: [
          {
            inlineData: {
              mimeType: "image/jpeg",
              data: imageBase64,
            },
          },
          { text: fullPrompt },
        ],
      },
    ],
  })

  const candidates = result.response.candidates
  if (!candidates || candidates.length === 0) {
    throw new Error("No response from Gemini API")
  }

  for (const part of candidates[0].content.parts) {
    if ((part as any).inlineData) {
      return (part as any).inlineData.data
    }
  }

  throw new Error("No image generated by Gemini API")
}

/**
 * Lightweight preview (lower resolution, prioritize speed).
 * Kicks off while user is still looking at the style grid.
 */
export async function generatePreview(
  imageBase64: string,
  stylePrompt: string
): Promise<string> {
  return generateSticker(imageBase64, stylePrompt + "\n\nPreview mode: ~512px resolution is fine, prioritize speed.")
}

/**
 * Full-resolution final for print. 1800x1800px @ 300 DPI = 6x6" print.
 */
export async function generateFinal(
  imageBase64: string,
  stylePrompt: string
): Promise<string> {
  return generateSticker(
    imageBase64,
    stylePrompt +
      "\n\nPrint mode: 1800x1800px, 300 DPI, sharp edges, high detail. This will be printed."
  )
}
