import OpenAI, { toFile } from "openai";

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY ?? "",
});

export async function generateStickerImage(
  imageBase64: string,
  stylePrompt: string
): Promise<string> {
  // Strip data URL prefix if present
  const base64Data = imageBase64.replace(/^data:image\/\w+;base64,/, "");
  const buffer = Buffer.from(base64Data, "base64");

  const imageFile = await toFile(buffer, "photo.png", { type: "image/png" });

  const response = await openai.images.edit({
    model: "gpt-image-1",
    image: imageFile,
    prompt: stylePrompt,
    quality: "high",
    background: "transparent",
    size: "1024x1024",
  });

  const outputBase64 = response.data?.[0]?.b64_json;
  if (!outputBase64) {
    throw new Error("No image generated by OpenAI");
  }

  let finalBase64 = outputBase64;

  // If remove.bg API key is available, run as a safety net to ensure
  // clean transparency for kiss-cut stickers
  const removeBgKey = process.env.REMOVEBG_API_KEY;
  if (removeBgKey) {
    try {
      const { removeBackground } = await import("@/lib/removebg");
      const cleanedDataUrl = await removeBackground(
        `data:image/png;base64,${outputBase64}`
      );
      finalBase64 = cleanedDataUrl.replace(/^data:image\/\w+;base64,/, "");
    } catch (e) {
      // remove.bg failed — use original (still has transparent background from OpenAI)
      console.warn("remove.bg fallback failed, using OpenAI output:", e);
    }
  }

  return `data:image/png;base64,${finalBase64}`;
}
